/* ---------------------------------------------------- */
/*  Generated by Enterprise Architect Version 16.1      */
/*  Created On : 06-may.-2025 6:17:33                   */
/*  DBMS       : MySql                                  */
/* ---------------------------------------------------- */

CREATE DATABASE sabor_currambero;
USE sabor_currambero;

SET FOREIGN_KEY_CHECKS=0;

/* Drop Tables */
DROP TABLE IF EXISTS `Favorito` CASCADE;
DROP TABLE IF EXISTS `Perfil_Gastronomico` CASCADE;
DROP TABLE IF EXISTS `Restaurante` CASCADE;
DROP TABLE IF EXISTS `Usuario` CASCADE;
DROP TABLE IF EXISTS `Valoracion` CASCADE;
DROP TABLE IF EXISTS `Visita` CASCADE;

/* Create Tables */

CREATE TABLE `Favorito` (
	`fecha_agregado` DATE NOT NULL,
	`id_usuario` INT NOT NULL,
	`id_restaurante` INT NOT NULL,
	CONSTRAINT `PK_Favorito` PRIMARY KEY (`id_usuario`, `id_restaurante`)
);

CREATE TABLE `Perfil_Gastronomico` (
	`id_perfil` INT NOT NULL AUTO_INCREMENT,
	`tipo_comida_fav` VARCHAR(100) NULL,
	`restricciones` TEXT NOT NULL,
	`presupuesto_promedio` INT NULL,
	`id_usuario` INT NOT NULL,
	CONSTRAINT `PK_Perfil_Gastronomico` PRIMARY KEY (`id_perfil`)
);

CREATE TABLE `Restaurante` (
	`id_restaurante` INT NOT NULL AUTO_INCREMENT,
	`nombre` VARCHAR(100) NOT NULL,
	`direccion` VARCHAR(200) NULL,
	`tipo_comida` VARCHAR(100) NOT NULL,
	`precio_promedio` INT NOT NULL,
	`latitud` DECIMAL(9,6) NULL,
	`longitud` DECIMAL(9,6) NULL,
	`calificacion_prom` DECIMAL(2,1) NOT NULL,
	`estado` BOOL NOT NULL,
	`instagram` VARCHAR(50) NULL,
	CONSTRAINT `PK_Restaurante` PRIMARY KEY (`id_restaurante`)
);

CREATE TABLE `Usuario` (
	`id_usuario` INT NOT NULL AUTO_INCREMENT,
	`primer_nombre` VARCHAR(50) NOT NULL,
	`segundo_nombre` VARCHAR(50) NULL,
	`primer_apellido` VARCHAR(50) NOT NULL,
	`segundo_apellido` VARCHAR(50) NULL,
	`correo` VARCHAR(50) NOT NULL,
	`contrasenia` VARCHAR(50) NOT NULL,
	`fecha_registro` DATETIME NOT NULL,
	`rol` ENUM('admin', 'cliente') NOT NULL,
	CONSTRAINT `PK_Usuario` PRIMARY KEY (`id_usuario`)
);

CREATE TABLE `Valoracion` (
	`id_valoracion` INT NOT NULL AUTO_INCREMENT,
	`calificacion` TINYINT UNSIGNED NOT NULL CHECK (`calificacion` BETWEEN 1 AND 5),
	`comentario` TEXT NULL,
	`fecha_valoracion` DATE NULL,
	`id_usuario` INT NOT NULL,
	`id_restaurante` INT NOT NULL,
	CONSTRAINT `PK_Valoracion` PRIMARY KEY (`id_valoracion`)
);

CREATE TABLE `Visita` (
	`id_visita` INT NOT NULL AUTO_INCREMENT,
	`fecha_visita` DATETIME NOT NULL,
	`id_usuario` INT NOT NULL,
	`id_restaurante` INT NOT NULL,
	CONSTRAINT `PK_Visita` PRIMARY KEY (`id_visita`)
);

/* Create Indexes and Uniques */

ALTER TABLE `Favorito` 
 ADD INDEX `IXFK_Favorito_Restaurante` (`id_restaurante`);

ALTER TABLE `Favorito` 
 ADD INDEX `IXFK_Favorito_Usuario` (`id_usuario`);

ALTER TABLE `Perfil_Gastronomico` 
 ADD CONSTRAINT `UN_Perfil_Gastronomico_Usuario` UNIQUE (`id_usuario`);

ALTER TABLE `Perfil_Gastronomico` 
 ADD INDEX `IXFK_Perfil_Gastronomico_Usuario` (`id_usuario`);

ALTER TABLE `Usuario` 
 ADD CONSTRAINT `UN_Correo` UNIQUE (`correo`);

ALTER TABLE `Valoracion` 
 ADD INDEX `IXFK_Valoracion_Restaurante` (`id_restaurante`);

ALTER TABLE `Valoracion` 
 ADD INDEX `IXFK_Valoracion_Usuario` (`id_usuario`);

ALTER TABLE `Visita` 
 ADD INDEX `IXFK_Visita_Restaurante` (`id_restaurante`);

ALTER TABLE `Visita` 
 ADD INDEX `IXFK_Visita_Usuario` (`id_usuario`);

/* Foreign Keys */

ALTER TABLE `Favorito` 
 ADD CONSTRAINT `FK_Favorito_Restaurante`
	FOREIGN KEY (`id_restaurante`) REFERENCES `Restaurante` (`id_restaurante`) ON DELETE RESTRICT ON UPDATE RESTRICT;

ALTER TABLE `Favorito` 
 ADD CONSTRAINT `FK_Favorito_Usuario`
	FOREIGN KEY (`id_usuario`) REFERENCES `Usuario` (`id_usuario`) ON DELETE RESTRICT ON UPDATE RESTRICT;

ALTER TABLE `Perfil_Gastronomico` 
 ADD CONSTRAINT `FK_Perfil_Gastronomico_Usuario`
	FOREIGN KEY (`id_usuario`) REFERENCES `Usuario` (`id_usuario`) ON DELETE RESTRICT ON UPDATE RESTRICT;

ALTER TABLE `Valoracion` 
 ADD CONSTRAINT `FK_Valoracion_Restaurante`
	FOREIGN KEY (`id_restaurante`) REFERENCES `Restaurante` (`id_restaurante`) ON DELETE RESTRICT ON UPDATE RESTRICT;

ALTER TABLE `Valoracion` 
 ADD CONSTRAINT `FK_Valoracion_Usuario`
	FOREIGN KEY (`id_usuario`) REFERENCES `Usuario` (`id_usuario`) ON DELETE RESTRICT ON UPDATE RESTRICT;

ALTER TABLE `Visita` 
 ADD CONSTRAINT `FK_Visita_Restaurante`
	FOREIGN KEY (`id_restaurante`) REFERENCES `Restaurante` (`id_restaurante`) ON DELETE RESTRICT ON UPDATE RESTRICT;

ALTER TABLE `Visita` 
 ADD CONSTRAINT `FK_Visita_Usuario`
	FOREIGN KEY (`id_usuario`) REFERENCES `Usuario` (`id_usuario`) ON DELETE RESTRICT ON UPDATE RESTRICT;

SET FOREIGN_KEY_CHECKS=1;
